version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          start: npm start
          executor: cypress/default
          wait-on: 'http://localhost:3000'
